version: '3.8'
services:
  mysql:
    container_name: minigameshub-docker-container
    image: mysql:latest
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    environment:
      #MYSQL_USER: root
      MYSQL_DATABASE: 'minigameshub_mysql_db'
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/minigameshub_mysql_db?autoReconnect=true&useSSL=false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    security_opt:
      - seccomp:unconfined
