version: '3.8'
services:
  mysql:
    container_name: minigameshub-docker-container
    image: mysql:latest
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: 'minigameshub_mysql_db'
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: 123456
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/minigameshub_mysql_db?autoReconnect=true&useSSL=false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    security_opt:
      - seccomp:unconfined

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
