spring:
  main:
    allow-circular-references: true
  application:
    name: minigameshub
  cloud:
    refresh:
      refreshable: none

SIGN_UP_TOKEN_EXPIRY_IN_HOURS: "3"
SECRET: "ajf98f3j4029roisSUUHDkad93290??hZzuI2"
FRONTEND_URL: "http://localhost:4200/"