spring:
  main:
    allow-circular-references: true
  application:
    name: minigameshub
  cloud:
    refresh:
      refreshable: none
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/minigameshub_db?autoReconnect=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update #create for drop previous data else update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL8Dialect # Allows Hibernate to generate SQL optimized for a particular DBMS